In [2]:
import torch
torch.__version__

'2.1.2+cu121'

In [3]:
# defining a scalar - a 0 dim tensor
scalar = torch.tensor(2)
scalar, scalar.ndim, scalar.shape

(tensor(2), 0, torch.Size([]))

In [4]:
# converting tensor to python integer
scalar_val = scalar.item()
scalar_val

2

In [5]:
#vector -> is a single dim tensor
vector = torch.tensor([1,2,3,4])
vector, vector.ndim, vector.shape

(tensor([1, 2, 3, 4]), 1, torch.Size([4]))

In [6]:
# matrix -> is 2 dimentional vector
matrix = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
matrix, matrix.ndim, matrix.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 2,
 torch.Size([3, 3]))

In [7]:
# tensor -> beyond 2 dim
tensor = torch.tensor([[[1,2,3], [4,5,6]]])
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6]]]),
 3,
 torch.Size([1, 2, 3]))

In [8]:
# creating a random tensor
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.0665, 0.9831, 0.6270, 0.8774],
         [0.6561, 0.7547, 0.6187, 0.3135],
         [0.4055, 0.1984, 0.2459, 0.8826]]),
 torch.float32)

In [9]:
# creating tensors filled with zeros and ones
zeros = torch.zeros(size=(3,3))
zeros, zeros.shape, zeros.ndim, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([3, 3]),
 2,
 torch.float32)

In [10]:
# zeros with custom type
# creating tensors filled with zeros and ones
zeros = torch.zeros(size=(3,3), dtype=torch.bool)
zeros, zeros.shape, zeros.ndim, zeros.dtype

(tensor([[False, False, False],
         [False, False, False],
         [False, False, False]]),
 torch.Size([3, 3]),
 2,
 torch.bool)

In [11]:
# similarly for ones
ones = torch.ones(size=(3,4), dtype=torch.int64)
ones, ones.shape, ones.dtype, ones.ndim

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 torch.Size([3, 4]),
 torch.int64,
 2)

In [12]:
# creating a tensor using range
tensor_range = torch.arange(start=0, end=10, step=2)
tensor_range, tensor_range.shape, tensor_range.ndim

(tensor([0, 2, 4, 6, 8]), torch.Size([5]), 1)

In [13]:
# creating tensors based on shape
zero_like = torch.zeros_like(tensor_range)
print(zero_like, zero_like.shape)

one_like = torch.ones_like(tensor_range)
print(one_like, one_like.shape)


tensor([0, 0, 0, 0, 0]) torch.Size([5])
tensor([1, 1, 1, 1, 1]) torch.Size([5])


In [14]:
# tensor operations
og = torch.tensor([1,2,3,4])

# add
sample  = og + 10
print(sample)

# sub
sample = og - 3
print(sample)

# mul
sample = og * 10
print(sample)

tensor([11, 12, 13, 14])
tensor([-2, -1,  0,  1])
tensor([10, 20, 30, 40])


In [15]:
#matrix multiplication

matmul = torch.matmul(og, og.T) # 1*4 * 4* 1 => 1*1
matmul.item()

/tmp/ipykernel_26052/4246429935.py:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3614.)
  matmul = torch.matmul(og, og.T) # 1*4 * 4* 1 => 1*1


30

In [16]:
# alternative
matmul = og @ og.T # 1*4 * 4* 1 => 1* -> this is slow (not recommended)
matmul.item()

30

In [17]:
# Linear Regression
#y = x * A(T) + b

torch.manual_seed(42)

X = torch.tensor([[1,2,3], [4,5,6],[5,6,7]], dtype=torch.float32)

linear = torch.nn.Linear(in_features=3, out_features=20)

y = linear(X)

print(X.shape, y.shape)

y

torch.Size([3, 3]) torch.Size([3, 20])


tensor([[ 1.0304,  0.2328,  2.1020,  0.7054,  1.5950,  0.9444, -0.2944,  0.2701,
         -1.8215, -2.2932,  1.3970,  0.9839,  1.7678, -0.8180,  1.7025,  0.2724,
         -2.5135,  0.5463,  1.3991,  0.1427],
        [ 3.3865,  1.7939,  3.8028,  1.2644,  3.9444,  2.2910, -1.4595,  0.5125,
         -4.4763, -4.8819,  2.8271,  1.7800,  3.6266, -1.3686,  4.9791,  0.8249,
         -4.4042, -0.0302,  3.1632,  0.2375],
        [ 4.1718,  2.3143,  4.3697,  1.4507,  4.7276,  2.7399, -1.8479,  0.5933,
         -5.3612, -5.7448,  3.3038,  2.0454,  4.2461, -1.5521,  6.0713,  1.0091,
         -5.0344, -0.2224,  3.7512,  0.2690]], grad_fn=<AddmmBackward0>)

In [18]:
# Aggregation

sample_tensor = torch.arange(0,20,3, dtype=torch.float32)
sample_tensor

tensor([ 0.,  3.,  6.,  9., 12., 15., 18.])

In [19]:
print("Min", sample_tensor.min())
print("Max",sample_tensor.max())
print("Medium", sample_tensor.median())
print("Mean", sample_tensor.mean())
print("Sum", sample_tensor.sum())


Min tensor(0.)
Max tensor(18.)
Medium tensor(9.)
Mean tensor(9.)
Sum tensor(63.)


In [20]:
# Positional min/max -> argmax, argmin

sample_arr  = torch.randn(size=(3,4), dtype=torch.float32)

sample_arr

tensor([[ 0.4679, -0.2049, -0.7409,  0.3618],
        [ 1.9199, -0.2254, -0.3417,  0.3040],
        [-0.6890, -1.1267, -0.2858, -1.0935]])

In [21]:
torch.argmax(sample_arr) # looks like the data needs to be normalized for this code to work

tensor(4)

In [22]:
torch.argmin(sample_arr)

tensor(9)

In [23]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [58]:
from collections import namedtuple

def arg_min_max(tensor: torch.tensor, max=True) -> list[int]:
    shape = list(tensor.shape)
    norm_tensor = tensor / tensor.max() # todo fix divide by zero
    if max:
        idx = norm_tensor.argmax()
    else:
        idx = norm_tensor.argmin()
    idx = idx.item()
    res = []
    for dim in shape[len(shape)-1:0:-1]:
        res.append((idx // dim))
        idx = idx % dim
    res.append(idx)
    return res

In [59]:
sample = torch.tensor([[1,2,11,4],[4,5,6,7], [8,9,10,3]])

In [60]:
print(arg_min_max(sample))
print(arg_min_max(sample, max=False))

[0, 2]
[0, 0]


In [61]:
# Reshaping 
sample.shape

torch.Size([3, 4])

In [64]:
new_tensor = sample.reshape(2,6) # or sample.view(2,6)
new_tensor.shape

torch.Size([2, 6])

In [66]:
new_tensor[0][0] = 9999

In [67]:
new_tensor, sample # changing the view affects the original tensor (reference)

(tensor([[9999,    2,   11,    4,    4,    5],
         [   6,    7,    8,    9,   10,    3]]),
 tensor([[9999,    2,   11,    4],
         [   4,    5,    6,    7],
         [   8,    9,   10,    3]]))

In [70]:
# stacking tensors
base_tensor = torch.tensor([1,2,3,4])

hstack = torch.stack([base_tensor, base_tensor], dim=0) # stacking in x dim

hstack, hstack.shape

(tensor([[1, 2, 3, 4],
         [1, 2, 3, 4]]),
 torch.Size([2, 4]))

In [71]:
vstack = torch.stack([base_tensor, base_tensor], dim=1) # stacking in x dim

vstack, vstack.shape

(tensor([[1, 1],
         [2, 2],
         [3, 3],
         [4, 4]]),
 torch.Size([4, 2]))

In [75]:
# squeeze - reduce a dim
not_sq = torch.tensor([[1,2,3,4]])
sq = torch.squeeze(not_sq)
not_sq, not_sq.shape, sq, sq.shape

(tensor([[1, 2, 3, 4]]),
 torch.Size([1, 4]),
 tensor([1, 2, 3, 4]),
 torch.Size([4]))

In [76]:
# Re-ordering the axes of a tensor

x_original = torch.rand(size=(224,224, 3))

x_permuted = x_original.permute(2,0,1)

print(x_original.shape, x_permuted.shape)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])


In [89]:
# Torch and Numpy

#torch.from_numpy() -> numpy -> torch
#torch.tensor.numpy() -> torch -> numpy

import numpy as np

np_arr = np.array([1,2,3])
trch_arr = torch.tensor([1,2,3], dtype=torch.long)

# checking for equality in numpy world
assert np.allclose(np_arr, trch_arr)
assert np.array_equal(np_arr, trch_arr)

In [90]:
# checking for equality in the torch world
assert  torch.allclose(trch_arr, torch.from_numpy(np_arr)) 
assert  torch.equal(trch_arr, torch.from_numpy(np_arr))

In [91]:
# Fiddling with GPU
torch.cuda.is_available()


True

In [92]:
# Count number of devices
torch.cuda.device_count()

2

In [94]:
# Putting tensors to gpu
tensor = torch.tensor([1,2,3])

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_on_gpu = tensor.to(device)

tensor_on_gpu, tensor_on_gpu.dtype, tensor, tensor.dtype

(tensor([1, 2, 3], device='cuda:0'),
 torch.int64,
 tensor([1, 2, 3]),
 torch.int64)

In [95]:
# moving the tensor from gpu to cpu and converting to numpy
np_arr = tensor_on_gpu.cpu().numpy()
np_arr, type(np_arr)

(array([1, 2, 3]), numpy.ndarray)